daemon off;
events { worker_connections 1024; }

rtmp {
    server {
        listen ${RTMP_PORT};
        chunk_size 4096;
		
        # OBS publish
		# EndPoint : rtmp://HOST:${RTMP_PORT}/live
		# RTMP URL EndPoint의 /live는 application 이름이며, application live {} 설정에 의해 결정된다.
        application live {
            live on;

            # RTMP -> HLS
			# RTMP ingest → (nginx 내부) HLS 패키징
			# hls on;
			# hls_path /var/www/hls;
			# hls_fragment 5;
			# hls_playlist_length 10;
			
			# FFmpeg 으로 hls 변환시 off 해야함.
            hls off;
        }
    }
}

http {
	# 응답 헤더/에러 페이지 등에 nginx 버전 노출을 줄임(보안/깔끔함)
    server_tokens off;
	
	# HTTP access log를 파일 대신 표준출력으로 보냄
	# Docker에서 로그 수집하기 좋음.
    access_log /dev/stdout combined; 

    server {
        listen ${HTTP_PORT};
		
		# 정적 파일 제공 루트 디렉토리
		# index.html을 찾는 기준.
		root /var/www/html;

		location = / {
		  try_files /index.html = 404;
		}

		# HLS 제공
        location /hls/ {
            alias /var/www/hls/;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
			
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        # DASH 제공
        location /dash/ {
            alias /var/www/dash/;
            types {
                application/dash+xml mpd;
                video/mp4 mp4 m4s;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
